# Generated by Django 3.1.3 on 2020-11-16 14:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2)),
                ('celular', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Número debe ser ingresado en formato '+549XXXXXXXXXX'.", regex='^\\+?549?\\d{8}$')], verbose_name='Celular')),
                ('historial', models.CharField(blank=True, max_length=200, verbose_name='Historial')),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('medico', models.CharField(blank=True, max_length=255)),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optometrialbye.pacientes')),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(choices=[('1', 'Cerca/Izquierda'), ('2', 'Cerca/Derecha'), ('3', 'Lejos/Izquierda'), ('4', 'Lejos/Derecha')], max_length=100)),
                ('otra_descripcion', models.CharField(choices=[('1', 'Con armazon'), ('2', 'Sin armazon')], max_length=50)),
                ('precio', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('pago', models.CharField(choices=[('1', 'Tarjeta'), ('2', 'Debito'), ('3', 'Efectivo'), ('4', 'Billetera Virtual')], max_length=100)),
                ('estado_pedido', models.CharField(choices=[('1', 'Pediente'), ('2', 'En taller'), ('3', 'Entregado')], max_length=60)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optometrialbye.pacientes')),
            ],
            options={
                'ordering': ['paciente'],
            },
        ),
    ]
